#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingMapsRESTToolkit
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MakingSpace")]
	public partial class AppointmentsTableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAppointment(Appointment instance);
    partial void UpdateAppointment(Appointment instance);
    partial void DeleteAppointment(Appointment instance);
    #endregion
		
		public AppointmentsTableDataContext() : 
				base(global::BingMapsRESTToolkit.Properties.Settings.Default.MakingSpaceConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public AppointmentsTableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppointmentsTableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppointmentsTableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AppointmentsTableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Appointment> Appointments
		{
			get
			{
				return this.GetTable<Appointment>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Appointments")]
	public partial class Appointment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVisit;
		
		private System.Nullable<System.DateTime> _DateVisited;
		
		private string _Appointments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVisitChanging(int value);
    partial void OnIdVisitChanged();
    partial void OnDateVisitedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateVisitedChanged();
    partial void OnAppointmentsChanging(string value);
    partial void OnAppointmentsChanged();
    #endregion
		
		public Appointment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVisit", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdVisit
		{
			get
			{
				return this._IdVisit;
			}
			set
			{
				if ((this._IdVisit != value))
				{
					this.OnIdVisitChanging(value);
					this.SendPropertyChanging();
					this._IdVisit = value;
					this.SendPropertyChanged("IdVisit");
					this.OnIdVisitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateVisited", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateVisited
		{
			get
			{
				return this._DateVisited;
			}
			set
			{
				if ((this._DateVisited != value))
				{
					this.OnDateVisitedChanging(value);
					this.SendPropertyChanging();
					this._DateVisited = value;
					this.SendPropertyChanged("DateVisited");
					this.OnDateVisitedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Appointments", DbType="VarChar(50)")]
		public string Appointments
		{
			get
			{
				return this._Appointments;
			}
			set
			{
				if ((this._Appointments != value))
				{
					this.OnAppointmentsChanging(value);
					this.SendPropertyChanging();
					this._Appointments = value;
					this.SendPropertyChanged("Appointments");
					this.OnAppointmentsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
